### ISSUE TITLE
Code Coverage

### ISSUE THREAD

**Issue by alextargov** [Teodor92/Project-Company-Life#9]
# What is the issue?
Is there a test code coverage minimum we should reach?

**Comment by Teodor92** [comment]
**Short answer:** No, there is no minimum percentage.

**Long answer:**

No, there is no hard minimum and I really don't want to give a minimum percentage for this. Why? Because this may lead to the creation of pointless tests that have no value to you, as a developers, and just artificially increase the code coverage.

That being said, you can strive to cover all of your source code with unit tests, BUT:
- I really do not recommend writing 'stupid' you tests, like testing if a getter gets, values, or if a setter set values.
- Use your common scene to determine what to test and what not to test.
- At the end of the day, this course is about Angular and not about unit testing, so you should prioritize accordingly.

Best,
Teodor
